### ISSUE TITLE
Priority todo's (most before, some after v.1)

### ISSUE THREAD

**Issue by theIDinside** [farre/midas#45]
(This issue will/can/should be updated if more things come up)
Implement the remaining relevant requests, some of which are on the following list. At the moment, not entirely sure about some of them if they make sense in the context of Midas.
- [x] attachRequest
- [x] dispatchRequest
- [x] setExceptionBreakpointRequest
- [ ] runInTerminalRequest
- [ ] gotoRequesst (not supported, rr reasons?)
- [ ] sourceRequest
- [ ] terminateThreadsRequest
- [ ] setExpressionRequest
- [ ] stepInTargetsRequest
- [ ] gotoTargetsRequest
- [x] completionRequest
- [x] exceptionInfoRequest
- [ ] loadedSourcesRequest
- [x] dataBreakpointInfoRequest
- [x] setDataBreakpointsRequest
- [ ] readMemoryRequest
- [ ] writeMemoryRequest
- [ ] disassembleRequest (partially implemented on the disassemble branch)
- [ ] cancelRequest
- [x] breakpointLocationsRequest
- [ ] setInstructionBreakpointsRequest
- [ ] restartFrameRequest (under rr easy, means more or less: reverse-finish, step in)

It's unclear, unfortunately, what requests of these VSCode even issue. So it very well may be that some of these requests do not even exist in VSCode. For instance, "supportedValueFormatting" doesn't do anything on VSCode, though it's clearly defined in the spec, and from what can be gathered on github and google, this only works for Visual Studio, not for VSCode. 

Beyond this, user testing of Midas is also required. Testing of debuggers can be tricky, and to some extent, testing a debugger interface can be even trickier (it seems to me, at least). It's hard to use unit testing (or integration testing) since, the debug testing suite existing for VSCode is pretty rudimentary. But it boils down to a few things, that we need to make sure works properly

That state, that works "normally" under the normal Midas configuration (i.e. non-rr version) does not break when the Midas-rr configuration is used. This involves things like; 
- [x] Keeping track of the stack and the stack frames. Since in rr, we can move forwards <-> backwards in an arbitrary fashion, we might have to scale back some of the state management that initially was implemented in order to make the extension work correctly. This isn't necessarily the case, but I've already ran into errors I could not explain in any other way, but seeing as how some of the requests aren't implemented, it could also be related to that. Either way, note to self, keep this in mind.

### Spawn rr in the same fashion as we do in rrcfg-tools
This means more or less consuming the code base from rrcfg-tools

This comes with questions like; what do we do with output from the inferior/tracee? When rr is in replay mode, it is the one outputting to stdout, not the tracing gdb process. So if we want this to be displayed in the debug console, we'll have to someone pipe the output from the rr process to us, and re-route it (via for instance console.log) to the debug console (i think?)

## SSH 
SSH functionality is of pretty high priority
